x-superset-user: &superset-user root
x-superset-volumes: &superset-volumes
  # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - ./docker/superset_config.py:/app/pythonpath/superset_config.py

services:
  db:
    image: postgres:latest
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Get from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env # Load variables from .env file
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
      - ./postgres/superset_init.sql:/docker-entrypoint-initdb.d/superset_init.sql
    networks:
      - my_network
  
  af:
    container_name: airflow_container
    image: apache/airflow:latest
    ports:
      - "8000:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
      _AIRFLOW_WWW_USER_USERNAME: admin
      WEATHER_API_KEY: ${WEATHER_API_KEY} # Get from .env
    env_file:
      - .env # Load variables from .env file
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./weather_api_pull:/opt/airflow/weather_api_pull
      - /var/run/docker.sock:/var/run/docker.sock
      - .env:/app/.env
    depends_on:
      - db
    networks:
      - my_network
    command: >
      bash -c "airflow db migrate && airflow standalone"

  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.0
    platform: linux/amd64
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
    env_file:
      - .env
    volumes:
      - ./dbt/dbt_project:/usr/app/
      - ./dbt:/root/.dbt
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /usr/app/
    depends_on:
      - db
    networks:
      - my_network
    command: run
    

  superset-init:
    env_file:
      - path: docker/.env # default
        required: true
    image: apache/superset:latest
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    user: *superset-user
    volumes: *superset-volumes
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
      DATABASE_DB: "superset_db"
    healthcheck:
      disable: true
    networks:
      - my_network


  superset:
    env_file:
      - path: docker/.env # default
        required: true
    image: apache/superset:latest
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app"]
    restart: unless-stopped
    ports:
      - 8088:8088
    user: *superset-user
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes: *superset-volumes
    environment:
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
      DATABASE_DB: "superset_db"
    networks:
      - my_network
  
  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis:/data
    networks:
      - my_network
  
volumes:
  redis:
    external: false  
    
networks:
  my_network:
    driver: bridge